import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./_components/navbar";
import { Toaster } from "../components/ui/sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          unsafe_disableDevelopmentModeWarnings: true,
        },
      }}
    >
      <html lang="en" className={`${GeistSans.variable}`}>
        <TRPCReactProvider>
          <body className="dark">
            <Navbar></Navbar>
            {children}
            <Toaster></Toaster>
          </body>
        </TRPCReactProvider>
      </html>
    </ClerkProvider>
  );
}
